### ISSUE TITLE
"Load all" hangs if tournaments are removed

### ISSUE THREAD

**Issue by nsunderland1** [UlyssesInvictus/QuizDB#17]
Steps to reproduce:

1. Enter and search the following query:
Category: mythology
Tournament: 2019 ACF Regionals, 2018 ACF Regionals
This should give you 29 tossups
2. Drop both tournaments from the query
3. Hit "Load all"

This causes quizdb to get stuck loading the questions

**Comment by UlyssesInvictus** [comment]
This is simply because the query is too wide, and too many results were loaded -- QuizDB has some built in limits to prevent the server from hanging as a result, but for whatever reason (e.g. server was just slow that day anyways, such as due to too much traffic), it hung when you loaded it.

Almost definitely not a technical issue, just a load one, so closing this for now. Feel free to reopen.
